-- SGBD: MySQL

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    ENDERECO_CLIENTE VARCHAR(200),
    TELEFONE_CLIENTE VARCHAR(20),
    EMAIL_CLIENTE VARCHAR(100)
);

-- Tabela VEICULO
CREATE TABLE VEICULO (
    ID_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
    PLACA_VEICULO VARCHAR(10) UNIQUE NOT NULL,
    MODELO_VEICULO VARCHAR(50) NOT NULL,
    MARCA_VEICULO VARCHAR(50) NOT NULL,
    ANO_VEICULO INT,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela ORDEM_SERVICO
CREATE TABLE ORDEM_SERVICO (
    NUMERO_OS INT PRIMARY KEY AUTO_INCREMENT,
    ID_VEICULO INT NOT NULL,
    DATA_EMISSAO_OS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ENTREGA_PREVISTA_OS DATE,
    VALOR_TOTAL_OS DECIMAL(10, 2),
    STATUS_OS ENUM('Em aberto', 'Em execução', 'Concluída', 'Cancelada') NOT NULL,
    FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID_VEICULO)
);

-- Tabela MECANICO
CREATE TABLE MECANICO (
    CODIGO_MECANICO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_MECANICO VARCHAR(100) NOT NULL,
    ENDERECO_MECANICO VARCHAR(200),
    ESPECIALIDADE_MECANICO VARCHAR(50)
);

-- Tabela SERVICO
CREATE TABLE SERVICO (
    ID_SERVICO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_SERVICO VARCHAR(200) NOT NULL,
    VALOR_MO_SERVICO DECIMAL(10, 2) NOT NULL
);

-- Tabela PECA
CREATE TABLE PECA (
    ID_PECA INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PECA VARCHAR(100) NOT NULL,
    DESCRICAO_PECA VARCHAR(200),
    VALOR_UNITARIO_PECA DECIMAL(10, 2) NOT NULL,
    QUANTIDADE_ESTOQUE_PECA INT
);

-- Tabela ITEM_SERVICO (Entidade de Ligação)
CREATE TABLE ITEM_SERVICO (
    NUMERO_OS INT NOT NULL,
    ID_SERVICO INT NOT NULL,
    QUANTIDADE_ITEM_SERVICO INT DEFAULT 1,
    VALOR_UNITARIO_ITEM_SERVICO DECIMAL(10, 2) NOT NULL,
    SUBTOTAL_ITEM_SERVICO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (NUMERO_OS, ID_SERVICO),
    FOREIGN KEY (NUMERO_OS) REFERENCES ORDEM_SERVICO(NUMERO_OS),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(ID_SERVICO)
);

-- Tabela ITEM_PECA (Entidade de Ligação)
CREATE TABLE ITEM_PECA (
    NUMERO_OS INT NOT NULL,
    ID_PECA INT NOT NULL,
    QUANTIDADE_ITEM_PECA INT NOT NULL,
    VALOR_UNITARIO_ITEM_PECA DECIMAL(10, 2) NOT NULL,
    SUBTOTAL_ITEM_PECA DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (NUMERO_OS, ID_PECA),
    FOREIGN KEY (NUMERO_OS) REFERENCES ORDEM_SERVICO(NUMERO_OS),
    FOREIGN KEY (ID_PECA) REFERENCES PECA(ID_PECA)
);

-- Tabela EQUIPE_OS (Entidade de Ligação)
CREATE TABLE EQUIPE_OS (
    NUMERO_OS INT NOT NULL,
    CODIGO_MECANICO INT NOT NULL,
    PRIMARY KEY (NUMERO_OS, CODIGO_MECANICO),
    FOREIGN KEY (NUMERO_OS) REFERENCES ORDEM_SERVICO(NUMERO_OS),
    FOREIGN KEY (CODIGO_MECANICO) REFERENCES MECANICO(CODIGO_MECANICO)
);
